### ISSUE TITLE
Make do not work

### ISSUE THREAD

**Issue by dubreuia** [johnkerl/miller#33] opened 2015-08-25 08:22 UTC
When I do `make` in a fresh git clone of the repo, I get:

    ./test/../mlr --icsv --odkvp cat test/input/null-fields.csv
    ./test/../mlr --inidx --odkvp cat test/input/null-fields.nidx
    ./test/../mlr --idkvp --oxtab cat test/input/missings.dkvp
    mlr --icsv --opprint cat test/input/utf8-1.csv
    ./test/run: 45: ./test/run: mlr: not found
    Makefile:116: recipe for target 'reg-test' failed
    make[1]: *** [reg-test] Error 127
    make[1]: Leaving directory '/home/dubreuia/Documents/program/johnkerl-miller/c'
    Makefile:7: recipe for target 'c' failed
    make: *** [c] Error 2

I think it is trying to execute the tests, with `mlr` but can't because it not yet installed.

I'm on gnome ubuntu 15.04.

**Comment by jungle-boogie** [comment] 2015-08-25 12:54
Hi @dubreuia,

But mlr should be at `miller/c/mlr` and the test should look `../c/mlr`. 

I think there's another bashism going on in `miller/c/test/run` and that's why it's failing.

**Comment by johnkerl** [comment] 2015-08-25 13:31
My apologies! A fix has been pushed.

**Comment by johnkerl** [comment] 2015-08-25 13:32
https://github.com/johnkerl/miller/commit/b9a502b6612e98d08622026caebde3705251db84

https://github.com/johnkerl/miller/commit/d70bd8115be8126483693cf30c616c21dde27cb0

**Closed by johnkerl** 2015-08-25 13:31 UTC

**Comment by jungle-boogie** [comment] 2015-08-25 13:39
:+1:

**Comment by johnkerl** [comment] 2015-08-26 02:13
Pending automated CI (https://github.com/johnkerl/miller/issues/15) right now I do manual CI -- before each commit, build with all unit and regression tests. That didn't catch this error, since `mlr` was in my `PATH`. For the time being I'm using an alias `alias minpath='export PATH=/usr/bin:/bin'` for the precommit build, which will help.
