### ISSUE TITLE
Inconsistent csv output (--ocsv) depending on input type

### ISSUE THREAD

**Issue by andrewflbarnes** [johnkerl/miller#455] opened 2021-03-25 23:11 UTC
Hello,

Having an issue when attempting to convert an array of simple json objects to csv. The output is inconsistent with my expectations as well as when using other formats (notably an equivalent csv form of the same data).

I've had a hunt around and don't see this raised as an existing issue or mentioned as a feature.

**What I'm trying**

Converting json data to csv data with a command like below where the input file is an array of simple objects (just kv pairs)
```bash
mlr --json --ocsv input.json
mlr --ijson --ocsv input.json
```

**What I expect**

The json data is converted to csv. For example given the data below as `input.json`
```json
[
  { "name": "Andrew", "drink": "tea", "location": "Bristol" },
  { "name": "Michelle", "location": "London" },
  { "name": "John", "drink": "coffee", "location": "London" }
]
```
I would expect the below output for one of the above commands
```csv
name,drink,location
Andrew,tea,Bristol
Michelle,,London
John,coffee,London
```

**What actually happens**

csv headers are generated once per record instead of once and each header-record is separated by a newline. In the example above I get the below output
```csv
name,drink,location
Andrew,tea,Bristol

name,location
Michelle,London

name,drink,location
John,coffee,London
```

I would expect the output to be the same for a couple of reasons
- the current output isn't a "valid" set of csv records with respect to the original input data
- the intermediate DKVP forms of the csv and json data (i.e. without specifying `--ocsv`) are the same with the exception of a missing kv pair when using json (the drink kv pair for the record with name "Michelle" below).

For the latter point as an example:
Given the above json data the DKVP form is
```bash
$ mlr --ijson cat input.json
name=Andrew,drink=tea,location=Bristol
name=Michelle,location=London
name=John,drink=coffee,location=London
```

Given equivalent csv data i.e.
```csv
name,drink,location
Andrew,tea,Bristol
Michelle,,London
John,coffee,London
```
the DKVP form is
```
$ mlr --icsv cat input.csv
name=Andrew,drink=tea,location=Bristol
name=Michelle,drink=,location=London
name=John,drink=coffee,location=London
```

**Other info**
```bash
$ brew info miller
miller: stable 5.10.2 (bottled), HEAD
Like sed, awk, cut, join & sort for name-indexed data such as CSV
https://github.com/johnkerl/miller
/usr/local/Cellar/miller/5.10.2 (6 files, 907.9KB) *
  Poured from bottle on 2021-03-25 at 17:22:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/miller.rb
License: BSD-2-Clause
==> Dependencies
Build: autoconf ✘, automake ✘, libtool ✔
==> Options
--HEAD
        Install HEAD version

$ mlr --version
Miller 5.10.2

$ uname -a
Darwin I09895 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

**Comment by aborruso** [comment] 2021-03-25 23:19
Your JSON input seems wrong, you should add commas

[

  { "name": "Andrew", "drink": "tea", "location": "Bristol" },

  { "name": "Michelle", "location": "London" },

  { "name": "John", "drink": "coffee", "location": "London" }

]



Il ven 26 mar 2021, 00:11 Barnesly ***@***.***> ha scritto:

**Comment by andrewflbarnes** [comment] 2021-03-25 23:34
@aborruso - thanks, was a copy paste error on my part when I was raising this (miller actually complains the json is invalid without the commas as it should) - I've updated the description :)

**Comment by aborruso** [comment] 2021-03-26 07:58
Hi @andrewflbarnes ,
the CSV has a rectangular shape: if you have 3 columns and 3 rows you must have 9 containers, 9 cells.

In a JSON you are free.

There is Miller verb to make a JSON become a rectangular CSV, it's [unsparsify](https://miller.readthedocs.io/en/latest/reference-verbs.html#unsparsify). If you run

```
mlr --j2c unsparsify input.json
```

you will have

```
name,drink,location
Andrew,tea,Bristol
Michelle,,London
John,coffee,London
```

I think that when the output is a CSV we should have [unsparsify by default](https://github.com/johnkerl/miller/issues/275), but I'm sure @johnkerl has a reason not to

**Comment by andrewflbarnes** [comment] 2021-03-26 10:41
Thanks @aborruso - `unsparsify` works great :)

I agree - sounds like `unsparsify` behaviour should be used in the case of json->csv.

Maybe more generally it should be used when converting between sparse and unsparse forms?

As a quick "fix" for now it might be worth updating the manpage and site info to mention using unsparsify (both under `cat` and `unsparsify` itself) when converting between sparse and unsparse formats. I think this might be most important under cat where on the manpage it specifies it is most useful for format conversions:
```
   cat
       Usage: mlr cat [options]
       Passes input records directly to output. Most useful for format conversion.
```

I think the issue is the underlying DKVP represnetation being equivalent which misleads user expectations. It's not transparent that there may have been an underlying change to the data nor that this will result in changes to output formats when you look at the manpage for `unsparsify` vs `cat`
```
   unsparsify
       Usage: mlr unsparsify [options]
       Prints records with the union of field names over all input records.
...
       Example: if the input is two records, one being 'a=1,b=2' and the other
       being 'b=3,c=4', then the output is the two records 'a=1,b=2,c=' and
```

**Bit of additional info**

If I update the `input.json` example above to include a `"drink": "orange juice"` entry for Michelle but not in the same order as the other records then I get the same issue
```bash
$ mlr --ijson --ocsv cat input.json
name,drink,location
Andrew,tea,Bristol

name,location,drink
Michelle,London,orange juce

name,drink,location
John,coffee,London
```

However if I add the drink entry in the same order then cat actually gives the same results as `unsparsify` i.e.
```bash
$ mlr --ijson --ocsv cat input.json
name,drink,location
Andrew,tea,Bristol
Michelle,orange juce,London
John,coffee,London
```

The below documentation reflects the latter case but it is unclear that differently ordered keys or missing keys breaks this.
http://johnkerl.org/miller-releases/miller-5.3.0/doc/10-min.html#Other-format_examples

Similarly looking at reference verbs below it is unclear that this is the behaviour with cat:
https://miller.readthedocs.io/en/latest/reference-verbs.html#cat

**Comment by johnkerl** [comment] 2021-03-26 14:32
Hi @andrewflbarnes, just saw this -- will take a look this weekend

**Comment by johnkerl** [comment] 2021-03-26 14:36
Hi @andrewflbarnes -- thanks for raising this!

Certainly, "user expectations" differ. Everything you noted here was intentional in the Miller implementation, including [the way Miller handles heterogeneous data.](https://miller.readthedocs.io/en/latest/record-heterogeneity.html).

There are certainly good opportunities for improved documentation -- thank you!

**Comment by johnkerl** [comment] 2022-02-24 04:11
This is a duplicate of https://github.com/johnkerl/miller/issues/275

**Closed by johnkerl** 2022-02-24 04:11 UTC
Labels: needs-documentation
