### ISSUE TITLE
How to use bash variable inside filter verb?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#209] opened 2018-12-09 18:03 UTC
Hi,
I have this kind of script

```bash
# a date
treGiorniFa=$(date -d "2 days ago" '+%Y-%m-%d')

# my filter
mlr --csv filter 'strptime($data, "%Y-%m-%d") < strptime('"$treGiorniFa"', "%Y-%m-%d")' ./MAria_report.csv
```

But it does not work. How can I pass a bash variable value to a filter expression?

Thank you

**Comment by aborruso** [comment] 2018-12-09 18:36
Hi,
I'm not able to save it using `bash -xv >./xv.txt`  :(

This is my error
```
treGiorniFa=$(date -d "2 days ago" '+%Y-%m-%d')
mlr --csv filter  'strptime($data, "%Y-%m-%d") < strptime('"$treGiorniFa"', "%Y-%m-%d")' ./MAria_report_long.csv
+ mlr --csv filter 'strptime($data, "%Y-%m-%d") < strptime(2018-12-07, "%Y-%m-%d")' ./MAria_report_long.csv
Expression does not evaluate to boolean: got MT_ERROR.
```

**Comment by aborruso** [comment] 2018-12-09 18:41
My input file

```
data,value,unita,frequenza,inquinante,stazione
2013-01-01,2.227614,(µg/m3),Max orario,SO2,partinico
2013-01-01,0.887651,(µg/m3),Media 24 h,SO2,partinico
2013-01-01,1.349516,(mg/m3),Max media 8h,CO,partinico
2013-01-01,123.068614,(µg/m3),Max orario,NO2,partinico
2013-01-01,34.898269,(µg/m3),Max media 8h,O3,partinico
2013-01-01,22.411990,(µg/m3),Media 24 h,PM10,partinico
2013-01-01,4.194134,(µg/m3),Max orario,Benzene,partinico
2013-01-01,41.493824,(µg/m3),Max orario,Benzene,Marcellino
2013-01-01,0.072567,(µg/m3),Max orario,SO2,enna
```

**Comment by johnkerl** [comment] 2018-12-09 23:00
You're only missing a pair of double quotes.

```
$ cat prima-prova.sh
treGiorniFa=$(date -v-2d '+%Y-%m-%d')
mlr --csv filter  'strptime($data, "%Y-%m-%d") < strptime('"$treGiorniFa"', "%Y-%m-%d")' ./MAria_report_long.csv
```

```
$ bash -xv prima-prova.sh
treGiorniFa=$(date -v-2d '+%Y-%m-%d')
date -v-2d '+%Y-%m-%d'
++ date -v-2d +%Y-%m-%d
+ treGiorniFa=2018-12-07
mlr --csv filter  'strptime($data, "%Y-%m-%d") < strptime('"$treGiorniFa"', "%Y-%m-%d")' ./MAria_report_long.csv
+ mlr --csv filter 'strptime($data, "%Y-%m-%d") < strptime(2018-12-07, "%Y-%m-%d")' ./MAria_report_long.csv
Expression does not evaluate to boolean: got MT_ERROR.
```

```
$ cat seconda-prova.sh
treGiorniFa=$(date -v-2d '+%Y-%m-%d')
mlr --csv filter  'strptime($data, "%Y-%m-%d") < strptime("'"$treGiorniFa"'", "%Y-%m-%d")' ./MAria_report_long.csv
```

```
$ bash -xv seconda-prova.sh
treGiorniFa=$(date -v-2d '+%Y-%m-%d')
date -v-2d '+%Y-%m-%d'
++ date -v-2d +%Y-%m-%d
+ treGiorniFa=2018-12-07
mlr --csv filter  'strptime($data, "%Y-%m-%d") < strptime("'"$treGiorniFa"'", "%Y-%m-%d")' ./MAria_report_long.csv
+ mlr --csv filter 'strptime($data, "%Y-%m-%d") < strptime("2018-12-07", "%Y-%m-%d")' ./MAria_report_long.csv
data,value,unita,frequenza,inquinante,stazione
2013-01-01,2.227614,(µg/m3),Max orario,SO2,partinico
2013-01-01,0.887651,(µg/m3),Media 24 h,SO2,partinico
2013-01-01,1.349516,(mg/m3),Max media 8h,CO,partinico
2013-01-01,123.068614,(µg/m3),Max orario,NO2,partinico
2013-01-01,34.898269,(µg/m3),Max media 8h,O3,partinico
2013-01-01,22.411990,(µg/m3),Media 24 h,PM10,partinico
2013-01-01,4.194134,(µg/m3),Max orario,Benzene,partinico
2013-01-01,41.493824,(µg/m3),Max orario,Benzene,Marcellino
2013-01-01,0.072567,(µg/m3),Max orario,SO2,enna
```

**Comment by johnkerl** [comment] 2018-12-09 23:01
(The slightly different `date` syntax is just because I'm using MacOSX.)

**Comment by aborruso** [comment] 2018-12-10 06:44
Oh, what a stupid error, thank you very much

**Comment by aborruso** [comment] 2019-07-08 09:39
@johnkerl another related question, if you have the time for it.

If I run 

```
echo 'input=2017-06-22T16:29:09.718382' | \
mlr --opprint --barred  put -S '$yearmonth="'"$(date -d2017-06-22T16:29:09.718382 +%m)"'"'
```

I have

```
+----------------------------+-----------+
| input                      | yearmonth |
+----------------------------+-----------+
| 2017-06-22T16:29:09.718382 | 06        |
+----------------------------+-----------+
```

How to use `input` field inside the put verb?

If I run

```
echo 'input=2017-06-22T16:29:09.718382' | \
mlr --opprint --barred  put -S '$yearmonth="'"$(date -d'$input' +%m)"'"'
```

The `input` value is not extracted

```
+----------------------------+-----------+
| input                      | yearmonth |
+----------------------------+-----------+
| 2017-06-22T16:29:09.718382 | -         |
+----------------------------+-----------+
```

Thank you

**Comment by johnkerl** [comment] 2019-07-10 02:07
https://github.com/johnkerl/miller/issues/246 would really help out here :)

**Comment by aborruso** [comment] 2019-07-10 05:47
@johnkerl I have read #246 but I'm not sure I understood it.

Reading it, it seems impossible to do it inside DSL. Am I wrong?

**Comment by johnkerl** [comment] 2019-07-10 14:00
#246 would make it easier for you to shell out to bash commands without having to play around with single-quotes. The feature doesn't exist yet.

**Comment by aborruso** [comment] 2019-07-11 08:52
@johnkerl wow, it would be great!!

**Comment by johnkerl** [comment] 2019-09-07 18:13
This is a duplicate of https://github.com/johnkerl/miller/issues/246

**Closed by johnkerl** 2019-09-07 18:13 UTC
