### ISSUE TITLE
Timezone-related tests failing

### ISSUE THREAD

**Issue by lcoombe** [johnkerl/miller#237] opened 2019-04-03 22:10 UTC
Hello,

`make check` is failing for me in ubuntu when running `brew install miller`:
```
==> make check
Last 15 lines from /root/.cache/Homebrew/Logs/miller/03.make:
make[5]: Leaving directory '/tmp/miller-20190403-19119-pc4yzd/mlr-5.4.0/c/reg_test'
Makefile:759: recipe for target 'check-TESTS' failed
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory '/tmp/miller-20190403-19119-pc4yzd/mlr-5.4.0/c/reg_test'
Makefile:857: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/tmp/miller-20190403-19119-pc4yzd/mlr-5.4.0/c/reg_test'
Makefile:546: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/tmp/miller-20190403-19119-pc4yzd/mlr-5.4.0/c/reg_test'
Makefile:584: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/tmp/miller-20190403-19119-pc4yzd/mlr-5.4.0/c'
Makefile:396: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
Example difference:
```
  mlr --opprint put $b=localtime2sec($a); $c=sec2localtime($b); $d=sec2localdate($b)
  a                   b                 c                   d
! 2017-02-18 23:00:00 1487469600.000000 2017-02-18 23:00:00 2017-02-18
```
```
  mlr --opprint put $b=localtime2sec($a); $c=sec2localtime($b); $d=sec2localdate($b)
  a                   b                 c                   d
! 2017-02-18 23:00:00 1487458800.000000 2017-02-18 23:00:00 2017-02-18
```

Any idea what is causing this?

@sjackman

**Comment by sjackman** [comment] 2019-04-03 22:25
The difference between 1487469600 and 1487458800 is 10,800 seconds or 3 hours.

**Comment by johnkerl** [comment] 2019-04-05 03:14
does anyone know when this started happening? i've pushed very few commits for some months now :(

**Comment by johnkerl** [comment] 2019-04-05 03:14
thanks @lcoombe and @sjackman for the debug

**Comment by johnkerl** [comment] 2019-04-05 03:15
@lcoombe I am guessing something involving the `TZ` environment variable, and given @sjackman's note, since I am east-coast US, I am guessing you are west-coast US/Canada?

**Comment by johnkerl** [comment] 2019-04-05 03:16
within `c/reg_test/run` I am not clearing `$TZ` and I probably should, for clean slate.

**Comment by johnkerl** [comment] 2019-04-05 03:22
so @lcoombe (1) can you tell me what your `$TZ` is? and (2) can you `export TZ=` and rerun your `make check`?

**Comment by sjackman** [comment] 2019-04-05 04:16
The `TZ` environment variable is unset. The local time zone is -0700 PDT. I suspect that `TZ=UTc make check` would also fail, and that `TZ=EST5PDT make check` would work.
Can you test that `TZ=PST8PDT make check` fails?

**Comment by sjackman** [comment] 2019-04-05 04:17
I'm curious why `make check` passes on macOS but fails on Linux. That's odd.

**Comment by sjackman** [comment] 2019-04-05 04:47
`make check` passes on CentOS 7 in PDT -0700.
`make check` fails on Ubuntu 18.04 in UTC+0000.

```console
$ TZ=UTC make check &>/dev/null; echo $?
2
$ TZ=PST8PDT make check &>/dev/null; echo $?
2
$ TZ=EST5EDT make check &>/dev/null; echo $?
2
```

There goes that theory. Changing the time zone seems to make no difference. This Ubuntu system is in a Docker image and has its local time zone set to UTC. Speaking of which, you should be able to reproduce this issue inside a `docker:xenial` container.

```console
$ apt-get install tzdata
$ TZ=UTC make check &>/dev/null; echo $?
0
$ TZ=PST8PDT make check &>/dev/null; echo $?
0
$ TZ=EST5EDT make check &>/dev/null; echo $?
0
```

So, `make check` requires the `tzdata` package to be installed. I can't say why. Any idea?

**Comment by terorie** [comment] 2019-12-24 16:13
Can reproduce, timezone-related tests only pass on Alpine Linux with `tzdata` installed.

**Comment by johnkerl** [comment] 2020-01-05 15:45
I guess I acknowledge this and list `tzdata` as an explicit dependency of Miller -- ?

**Comment by terorie** [comment] 2020-01-06 13:58
@johnkerl It seems like a development dependency for sure, otherwise the tests fail.
If I understand correctly, without `tzdata` it defaults to UTC (since other time zones are not installed), otherwise it uses the local time.
That seems like the correct behavior, right?
Maybe it's enough to add a remark to the manpage and `localtime2sec` reference and add `tzdata` recommended packages section instead of dependencies?
Otherwise we would force a system-wide change with potential side effects on other programs.

**Comment by johnkerl** [comment] 2020-01-06 14:43
Makes sense -- thanks!

**Comment by johnkerl** [comment] 2021-11-17 16:46
HI @lcoombe @sjackman @terorie -- sorry for the delay -- I've rewritten Miller in Go & will be releasing it as Miller 6 soon.

Of course the datetime-library issue is entirely different between C and Go.

Looking at https://pkg.go.dev/time/tzdata@go1.17.3 it looks like I'll need to build with `-tags timetzdata` to ensure fallback behavior. It doesn't look like I have a Linux system _without_ `tzdata` installed so let's leave this open for the moment.

**Comment by terorie** [comment] 2021-11-19 19:12
> I've rewritten Miller in Go

@johnkerl That is an incredible update for being mentioned so casually. Congrats on this milestone! 🎉 

> Of course the datetime-library issue is entirely different between C and Go.
> ...
> It doesn't look like I have a Linux system without tzdata installed so let's leave this open for the moment.

As far as I'm concerned, it is not possible to reproduce the original issue when running `make check` anymore. So maybe it's best to close this issue and re-open if a similar problem reoccurs in the Go version. Meanwhile I'll test this in an Alpine Linux without tzdata installed to see if I can reproduce. But I've worked with Go for years and never seen a discrepancy with time zones myself. 😅

**Comment by johnkerl** [comment] 2021-11-19 19:50
OK @terorie thanks!

@lcoombe I will close this I suppose unless as original asker you have more info here -- please let me know and we can reopen.

**Closed by johnkerl** 2021-11-19 19:50 UTC
Labels: go-port
