### ISSUE TITLE
tail -f and miller

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1142] opened 2022-12-08 15:02 UTC
@johnkerl I open an issue, because in your answer you talk about bug and regression.

Thank you

### Discussed in https://github.com/johnkerl/miller/discussions/1117

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** October 26, 2022</sup>
Hi,
I have the below input file.

Using miller 5 I can monitor on screen file change using 

```
tail -f input.csv | mlr --icsvlite --otsv --ifs "," cat
```

If I use Miller 6 I have no output on screen.

If in miller 5 I change my command in

```
mlr --icsvlite --opprint --ifs "," cat input.csv
```

I have no output.

Am I doing something wrong? Is there a more correct way to do it?
I would like to use Miller to monitor file changes, because I need to print better tail output on screen.

Thank you

```
data,stato,codice_regione
5,ITA,08
2,ITA,08
3,ITA,10
```</div>

**Comment by johnkerl** [comment] 2023-03-04 04:27
@aborruso for `--opprint` no output is printed until all input is read. This is because PPRINT format requires knowing the max width down all columns. This was true in Miller 5 and 6. See also https://miller.readthedocs.io/en/latest/file-formats/#pprint-pretty-printed-tabular.

For the `--otsv` case in Miller 6 this is a problem and I think it's related to #1178.

**Comment by johnkerl** [comment] 2023-03-04 04:30
... confirmed.

For now you need

```
tail -f input.csv | mlr --records-per-batch 1 --icsvlite --otsv --ifs "," cat
```

which is admittedly awkward. 😞 

I'll close this issue since #1178 is still open.

**Closed by johnkerl** 2023-03-04 04:30 UTC
Labels: bug
