### ISSUE TITLE
FYI: Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [johnkerl/miller#338] opened 2020-06-05 11:51 UTC
I created automatic chocolatey package. It will follow your releases here.
- https://chocolatey.org/packages/miller

Package source code:
- https://github.com/majkinetor/au-packages/tree/master/miller

**Comment by aborruso** [comment] 2020-06-05 12:33
Thank you

**Comment by johnkerl** [comment] 2020-06-05 15:43
Awesome thanks!!!! :)

**Comment by johnkerl** [comment] 2020-08-18 13:21
Hi @majkinetor -- what are the steps for getting [Miller 5.8.0](https://github.com/johnkerl/miller/releases/tag/v5.8.0) into Chocolatey?

**Comment by majkinetor** [comment] 2020-08-18 13:24
None. Its automatic.

You can always check latest status here:

https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#miller

Currently:

```
ignored

miller - checking updates using au version 2020.8.18.10024
Can't find windows release
```

**Comment by johnkerl** [comment] 2020-08-18 13:25
OK, do I need to do anything? The Appveyor build is broken and it's really confusing me. Does Chocolatey require the Appveyor-produced artifacts as inputs to Chocolatey?

**Comment by majkinetor** [comment] 2020-08-18 13:29
Yes, you need to provide windows build.

Technically, package update procedure can do anything including building its own version, but that is almost never done and people and choco admins rely on official builds.

Also, its only appropriate that build is fixed here rather IMO.

So, we need some binaries, no matter where they are (if not released on Github releases I need to update the scripts). You don't need to use AV tho, you can go with GH Actions or whatever.

**Comment by johnkerl** [comment] 2020-08-18 14:21
OK thanks!! I'll try GH actions. The AppVeyor issue has me baffled, despite a goodly amount of googling ... :(

**Comment by johnkerl** [comment] 2020-08-18 14:33
The issue is that these build commands

https://github.com/johnkerl/miller/blob/master/appveyor.yml

are resulting in this error message

https://ci.appveyor.com/project/johnkerl/miller

**Comment by majkinetor** [comment] 2020-08-18 19:40
I suggest you use Remote Desktop to log in to AV and interactively try to resolve the problem.

**Comment by johnkerl** [comment] 2020-08-19 12:29
@majkinetor awesome, thanks for the advice!!!! :)

**Comment by johnkerl** [comment] 2020-08-19 18:16
The AppVeyor build was fixed in a sequence of commits ending at https://github.com/johnkerl/miller/issues/354

At this point, since there is a [new `.mlrrc` feature](https://github.com/johnkerl/miller/issues/339), I'll probably just go ahead and make a 5.9.0 release, and it'll have Windows artifacts in it ... @majkinetor will this work for Chocolatey?

**Comment by johnkerl** [comment] 2020-08-20 01:53
https://chocolatey.org/packages/miller already has the latest 5.9.0 :)

**Comment by majkinetor** [comment] 2020-08-20 07:58
Yeah, the maximum latency is one day.
Glad you fixed the build.

**Comment by johnkerl** [comment] 2022-01-11 03:08
Hi @majkinetor ! There's a new https://github.com/johnkerl/miller/releases/tag/v6.0.0 which is a re-write -- it's in Go now; no more MSYS2; etc.

Now the build artifact is called `mlr-windows-latest.zip` with a `mlr.exe` inside of it; no more `.dll`.

Also at https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1 I wasn't how the build error `flameshot: Invalid version: 11.0.rc1` is related to Miller ...

**Comment by majkinetor** [comment] 2022-01-11 09:26
OK, I will update the package, but it will have to wait few days...

> Also at https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1 I wasn't how the build error flameshot: Invalid version: 11.0.rc1 is related to Miller ...

Its not related to miller. Miller is ignored currently:

![image](https://user-images.githubusercontent.com/85767/148916251-4e4080e6-f03e-4797-9713-84e4d7197503.png)

**Comment by johnkerl** [comment] 2022-01-11 12:56
Thanks @majkinetor !

**Comment by johnkerl** [comment] 2022-01-12 03:27
I saw the update -- thanks @majkinetor ! :)

**Closed by johnkerl** 2022-01-12 03:27 UTC
Labels: needs-documentation
