### ISSUE TITLE
Add an option to not buffer output?

### ISSUE THREAD

**Issue by BonkaBonka** [johnkerl/miller#399] opened 2020-12-15 20:47 UTC
As far as I can tell, miller buffers the most recent line received in a pipeline.

If I run in one window:
~~~
inotifywait --quiet --monitor --event moved_to --event close --include '\.md$' --csv /tmp/ | mlr --icsv --implicit-csv-header --ojson label dir,operations,filename
~~~

And then in a second window I do:
~~~
touch /tmp/one.md && touch /tmp/two.md && touch /tmp/three.md
~~~

I get the output:
~~~
{ "dir": "/tmp/", "operations": "CLOSE_WRITE,CLOSE", "filename": "one.md" }
{ "dir": "/tmp/", "operations": "CLOSE_WRITE,CLOSE", "filename": "two.md" }
~~~

`three.md` won't show up unless I cause more events.

**Comment by johnkerl** [comment] 2020-12-16 22:10
@BonkaBonka I'll need to dig into this one a bit. Miller tries hard *not* to buffer ... there's in fact a `--no-fflush`. A couple exceptions are JSON input is non-streaming (no records are delivered for a file until end of file) -- fixed in the [Go port](https://github.com/johnkerl/miller/issues/372) -- and PPRINT output which produces no output until all records have been read. The latter is by design: it needs to see max-widths down all columns.

Anyway, neither of those are the case here so something else more subtle must be going on ...

**Comment by agguser** [comment] 2021-01-16 03:50
Workaround: add blank records and skip them
```
inotifywait --quiet --monitor --event moved_to --event close --include '\.md$' --csv /tmp/ |
   sed -u 's/$/\n,,/' |
   mlr --icsv --implicit-csv-header --ojson label dir,operations,filename \
      then skip-trivial-records
```

**Comment by johnkerl** [comment] 2021-02-09 03:49
@BonkaBonka I'm glad you had a workaround -- I was never able to reproduce this, and I'm hoping that with the redesign in the Go port this will not be an issue. If I'm wrong, we can reopen/revisit later.

And @agguser thanks for the workaround!! :D

**Closed** 2021-02-09 03:50 UTC
