### ISSUE TITLE
Documentation of flatten and split*/join*

### ISSUE THREAD

**Issue by Poshi** [johnkerl/miller#908] opened 2022-01-29 19:00 UTC
More documentation details.
`flatten` method does not have a complete description. It explains what it does, but it does not explain which are the arguments. You have to look and understand the examples to grasp the meaning. The usage should be clear from the description itself.

Similarly, for `join*` and `split*`, the different arguments are not clear without looking at the examples. Some assumptions could be made, like the parameters for `joink` are the array/map keys and the string to use to make the join. But what about `joinkv`? Which parameter is the separator of key and value and which parameter is the separator of records? In fact, the current implementation is antiintuitive: the `joink` and `joinv` methods use the second argument for the record separator while the `joinkv` uses the third field for that and the second field is used for the key-value separator.

**Comment by Poshi** [comment] 2022-01-29 19:34
Instead of opening a new issue, I will add more comments on DSL documentation here.
There are a few string functions that are not much documented. `gsub` and `sub` are barely documented, but you can understand what they do. But `regextract` is different. It seems to extract a substring that matches the regex pattern, but what happens when there are several matches in the string? It returns the first? The last? (Same doubts in `sub`). If the user uses capture groups in `regextract`, would they work?

`ssub` is described as `sub` without regexing. But `sub` is just described as "replace once" and the example uses plain text. If regex can be used in `sub` (and `gsub`) it would be good to state that in the documentation.

`strftime` refers to the C library for the format string. Should it be the Go library?

Obvious TODO work: `systime`, `systimeint` and `uptime` just have placeholders for the help string :-)

Semantic comment:
`is_not_empty  (class=typing #args=1) False if field is present in input with empty value, true otherwise` -> That means that and absent value will return true. While technically it makes sense, many people will ask if "is not empty" to get the green flag before processing the value, which will be inexistent if the field is absent. Would it make sense to consider absent fields as empty ones? Probably you already though about those concerns, but just in case.

**Comment by johnkerl** [comment] 2022-02-01 05:13
Tracking on https://github.com/johnkerl/miller/pull/913

**Comment by Poshi** [comment] 2022-02-04 22:46
In `reference-dsl-time` page, near the end, in the relative times section, the first example does not contain the command line used to generate the shown data.

**Comment by johnkerl** [comment] 2022-02-05 05:19
Hi @Poshi thanks for all of these!! :)

Can you please take a look now that https://github.com/johnkerl/miller/pull/913 and https://github.com/johnkerl/miller/pull/921 are merged?

I believe I have all of these addressed (please let me know what you think, if there's more that we should do) -- except for the bit about absent & empty.

The idea of 'absent' in Miller was a key part of the design from the very beginning, and it plays an essential role in the DSL -- given heterogeneous data (like JSON, DKVP, etc.) it's a "magic syntax" that lets you do things like `$z=$x+$y` without needing to check if a given record has `$x` and/or `$y` in it -- if it has both, the assignment to `$z` will happen, else it won't. This was clever, but I have some regrets about it now. Principally since I have the same absent logic for local variables -- so `z=x+y` also results in no assignment if either `x` or `y` is undefined. This makes DSL expressions confusing & hard to debug in case of typos :(. There the functions like `asserting_present`, but they're wordy/keystrokey as well as opt-in on every single utterance, and typedecls like `var` which provide some help but not enough.

The distinction between absent and empty is essential to maintain, but it needs to be improved to do the right thing nearly as often, and the wrong thing much less often than now.

I'd like to improve on the issues noted above with, perhaps, a "strict mode" (https://github.com/johnkerl/miller/issues/440).

**Comment by Poshi** [comment] 2022-02-06 13:19
`flatten` documentation is a lot clearer now. I don't like the fact that the parameter meaning changes with the number of arguments, but it is how it has been designed, so nothing to say here.

You improved the `join*` descriptions, but the `split*` ones are still obscure. I can see than there's a lot of redundancy between all of them, but a user looking for the description of splitkvx only sees: `splitkvx  (class=conversion #args=3) Splits string by separators into map without type inference (keys and values are strings).`. The user knows that there are three arguments, one of them must be the string, another the separator and a third unknown one. Unless the user also check `join*` documentation or the example at hand, function usage is not clear.

`gsub`, `sub`, `ssub` and `regextract` now looks good as a group! :-)

`strftime` is still somewhat ambiguous. It starts talking about the C library and adding that this is mostly the same. Then points the user to the page where the differences are stated. I'm not sure if it would be better to point users to the Go documentation (more correct, less ubiquitous) or leave it as it is (not so correct, more ubiquitous (`man strftime`)).

Regarding the absent/empty distinction... I like your perspective, but I still feel that the `is_not_empty` is not returning the proper value:
```
$ mlr -n put 'end {print(is_absent(a)); print(is_not_empty(a))}'
true
true
```
I'm seeing that something absent is not empty. How can be not empty something that does not exist?
Following your logic, `is_not_empty` of an absent value should not evaluate or return absent value. Neither true nor false.
Maybe there's no solution to that semantic issue while keeping the main point for the introduction of absents: reduce keystrokes, simplify code and get correct results. But those results really sounds ugly to me.

**Comment by Poshi** [comment] 2022-02-06 13:20
Another issue with the documentation: I'm not completely sure, but I think that `-s` flag is not explained. There are mentions and examples of use in the documentation, but a proper explanation of what it does... I cannot find it. It does not appear in `mlr help flags` either.

**Comment by johnkerl** [comment] 2022-02-06 16:20
> Another issue with the documentation: I'm not completely sure, but I think that -s flag is not explained. There are mentions and examples of use in the documentation, but a proper explanation of what it does... I cannot find it. It does not appear in mlr help flags either.

@Poshi good call & thank you! https://github.com/johnkerl/miller/pull/926

**Comment by johnkerl** [comment] 2022-02-06 17:18
@Poshi re splitters: thanks! In my exuberance I'd checked joiners & splitters off my to-do list, but clearly, had only done the former not the latter.

Please see https://github.com/johnkerl/miller/pull/927

**Comment by johnkerl** [comment] 2022-02-06 17:18
> I'm seeing that something absent is not empty. How can be not empty something that does not exist?
Following your logic, is_not_empty of an absent value should not evaluate or return absent value. Neither true nor false.
Maybe there's no solution to that semantic issue while keeping the main point for the introduction of absents: reduce keystrokes, simplify code and get correct results. But those results really sounds ugly to me.

Ah, you're definitely right. Thanks for persisting. :)

**Comment by johnkerl** [comment] 2022-02-06 18:39
@Poshi https://github.com/johnkerl/miller/pull/929

**Comment by Poshi** [comment] 2022-02-07 22:18
In 10min doc page, section "Filtering". The second example have no output. I tested the command and it is returning nothing. I tried several variations, but I didn't managed to filter by a boolean field :-?
The tests I've done, all with empty output:
```
$ mlr --icsv --opprint filter '$color == "red" && $flag == true' https://miller.readthedocs.io/en/latest/example.csv
$ mlr --icsv --opprint filter '$color == "red" && $flag == True' https://miller.readthedocs.io/en/latest/example.csv
$ mlr --icsv --opprint filter '$color == "red" && $flag == (1==1)' https://miller.readthedocs.io/en/latest/example.csv
$ mlr --icsv --opprint filter '$color == "red" && $flag == false' https://miller.readthedocs.io/en/latest/example.csv
$ mlr --icsv --opprint filter '$flag == true' https://miller.readthedocs.io/en/latest/example.csv
```

**Comment by johnkerl** [comment] 2022-02-07 23:58
@Poshi indeed, and thank you -- after a few reported issues I decided not to auto-infer `Infinity`, ` true`, etc to float/boolean respectively when they appear in data files.

What you found is a holdover from before that.

https://github.com/johnkerl/miller/pull/931

**Comment by Poshi** [comment] 2022-02-08 08:39
You are right. If I use `"true"` (as string, not boolean), it works.
I don't know which where the issues with inferring booleans and infinities but, if this have to do with their representation, you could add parameters to explicitly tell which would be the string(s) that represent the required values. Something like: `--symbol-true yes --symbol-false off --symbol-infinity inf --symbol-not-available N/A`

**Comment by johnkerl** [comment] 2022-02-08 12:43
@Poshi the issue is data files.`typeof(true)` is `bool`, as expected.

```
$ mlr repl

[mlr] x = true
[mlr] x
true
[mlr] typeof(x)
"bool"

[mlr] y = 0/0
[mlr] y
NaN
[mlr] typeof(y)
"float"
[mlr]
```

The issue is text columns in data files. If a column has all words in it, it turns out (via their reports) are not happy when they've got words in a column and a few of them randomly infer to non-string.

Example:

```
$ cat input.csv
n,text
1,is
2,it
3,true
4,that
5,infinity
6,is
7,not
8,a
9,number
10,but
11,a
12,process?
```

This is not wanted:

```
$ mlr --c2p --from input.csv put '$tx = typeof($text)'
n  text     tx
1  is       string
2  it       string
3  true     bool
4  that     string
5  infinity float
6  is       string
7  not      string
8  a        string
9  number   string
10 but      string
11 a        string
12 process? string
```

**Comment by johnkerl** [comment] 2022-02-08 12:48
> Which is the type of a string compared to a boolean? That should trigger some kind of error.

@Poshi it doesn't, and never has in Miller. Things of different types are simply not equal to one another, unless cast to the same type. The exception is that [Miller tries hard to make a smooth "number" type](https://miller.readthedocs.io/en/latest/reference-main-arithmetic/) that non-software-engineers can reason correctly about without knowing details of machine arithmetic like twos-complement integers and IEEE floating point.

```
$ mlr repl

[mlr] true == "hello"
false
[mlr] true == "true"
false
[mlr] true == boolean("true")
true
[mlr] string(true) == "true"
true
[mlr] 1 == 1.0
true
```

**Comment by johnkerl** [comment] 2022-02-08 12:49
> Something like: --symbol-true yes --symbol-false off --symbol-infinity inf --symbol-not-available N/A

This sounds like a good feature addition! :)

**Comment by Poshi** [comment] 2022-02-08 20:05
> The issue is text columns in data files. If a column has all words in it, it turns out that Miller users (via their reports) are not happy when they've got words in a column and a few of them (seemingly randomly) infer to non-string.
> 
> People ended up wrapping fields in things like `string($name)` which is overly frictional.

Hummm... I see the issue, but you just moved the issue from the "literary" people to the "logic" people. Now, any data analyst that does not have random words in their columns but boolean data will have to wrap fields in things like `boolean($name)`, which is overly frictional.

The main issue is that every record gets its own type inference. The types are not inferred by column, but by record. A mostly working workaround (but not always) would be to associate a type to a column/key the first time data for that key is read. For truly boolean columns, the type will be boolean, and for string columns... the data will be string unless the first entry looks like a boolean.

There's no way to solve that issue while keeping the streaming ability and not asking the user. We clearly want to keep the streaming ability, so maybe we can ask the user to specify types when ambiguities can happen. Something in the line `--column-types ColumnName1,string,ColumnName4,boolean`. It adds complexity, but as long as everything works automatically by default and the user have the option to specify the types when needed, that complexity is hidden until required.
Or just let the user `put` a type coercion in every record :-)

**Comment by johnkerl** [comment] 2022-02-08 21:30
> you just moved the issue from the "literary" people to the "logic" people

Correct -- this is where I want the _default_ to be. People have complained about unwanted inference, not about unwanted non-inference.

And agreed, no one behavior can satisfy everyone -- while the default should be judiciously chosen, there can, and should, be better ways to override the default for people who want it. You've raised several great ideas for doing so -- I really appreciate that! :)

**Comment by Poshi** [comment] 2022-02-08 22:46
In `repl`, the `:context` command is shown in an example, but not mentioned elsewhere. It is clear what it does... but it should be in the theoretical part of the documentation, not only in the practical.

**Comment by Poshi** [comment] 2022-02-08 22:52
`mlr help function non-existent-function-name` returns nothing. An error message telling that the function does not exist would be nice.
(sorry, this is not a documentation issue, but I found it just by reading the documentation XD)

**Comment by johnkerl** [comment] 2022-02-08 23:19
> `mlr help function non-existent-function-name` returns nothing. An error message telling that the function does not exist would be nice.

@Poshi https://github.com/johnkerl/miller/pull/934

**Comment by Poshi** [comment] 2022-02-17 14:45
`funct` does not appear in the list of types, but can be used, at least, to declare the type of an argument to a function. I'm not sure if a function can also be returned and `funct` used as the return type of a function :-?

In any case, this keyword is quite hidden in the runtime help and almost not mentioned in the online documentation.

**Comment by johnkerl** [comment] 2022-02-17 15:00
@Poshi good call and thank you! This does indeed need examples.

Just for information / sneak peek:

* `funct` is indeed the type for function literals, either as arguments or as return types
* Implementation detail: using `func` in the grammar led to parsing ambiguities, so I used `funct` (_function type_) instead

```
$ cat funct-example.mlr
func mkfunc(): funct {
  return func(x,y) {
    return 10*x + y
  }
}

func callfunc(funct f, num x, num y): num {
  return f(x, y)
}
```

```
$ rlwrap mlr repl
Miller 6.0.0-dev REPL for darwin/amd64/go1.17
Docs: https://miller.readthedocs.io
Type ':h' or ':help' for online help; ':q' or ':quit' to quit.

[mlr] :load funct-example.mlr

[mlr] f = mkfunc()

[mlr] f
function-literal-000001

[mlr] f(2,3)
23

[mlr] callfunc(f, 3, 5)
35
```

**Comment by Poshi** [comment] 2022-02-18 11:44
In `reference-verbs` page I saw some HTML "bare" entities. In the `histogram` documentation, the literal `&le;` appears instead of the expected `<=`. 
The `*.md.in` contains `&le;`, which is translated to the same in the `*.md` output. But in the final HTML page it gets converted to `&amp;le;` so the final user sees the `&le;`.
I don't know where this conversion is made, so I leave it to you to solve this small issue :-)

**Comment by johnkerl** [comment] 2022-02-22 05:36
@Poshi https://github.com/johnkerl/miller/pull/961 re `funct` keyword

**Comment by johnkerl** [comment] 2022-02-24 02:06
@Poshi https://github.com/johnkerl/miller/pull/964

**Comment by johnkerl** [comment] 2022-02-24 02:18
Thanks @Poshi for all the amazing feedback!!!! 🗡️ 

Closing this issue; if there are other items, let's open separate issues for tracking.

**Closed by johnkerl** 2022-02-24 02:18 UTC
Labels: pending feedback to close, active, needs-documentation
