### ISSUE TITLE
mlr:./.libs/lt-mlr.c:233: FATAL: couldn't find mlr.

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#148] opened 2017-07-12 17:12 UTC
Hi John,

I'm wanting to try out miller on windows 7.

I already have a path set for other small executable on my system, so I don't think it's a path problem.

I receive this error when running mlr:

```
C:\Users\jungle\bin>mlr
mlr:./.libs/lt-mlr.c:233: FATAL: couldn't find mlr.
```

```
C:\Users\jungle\bin\mbin>mlr
mlr:./.libs/lt-mlr.c:233: FATAL: couldn't find mlr.
```

```
 Directory of C:\Users\jungle\bin\mbin

07/12/2017  10:08 AM    <DIR>          .
07/12/2017  10:08 AM    <DIR>          ..
07/12/2017  10:01 AM           281,871 libpcre-1.dll
07/12/2017  10:01 AM            44,554 libpcreposix-0.dll
07/12/2017  10:00 AM            37,888 mlr.exe
               3 File(s)        364,313 bytes
               2 Dir(s)  513,213,227,008 bytes free
````

What am I doing wrong? I am using this build: https://github.com/johnkerl/miller/releases/tag/v5.2.0

**Comment by johnkerl** [comment] 2017-07-12 21:33
Bummer! Do you know if this is a 32-bit system or a 64-bit system?

**Comment by johnkerl** [comment] 2017-07-12 21:35
What I've been building is definitely 64-bit artifacts

**Comment by jungle-boogie** [comment] 2017-07-13 05:03
Hi John,

It's windows 7 64 bit.

Thanks!

**Comment by jungle-boogie** [comment] 2017-07-17 00:30
Hi @johnkerl,

Any suggestions?

Thanks!

**Comment by johnkerl** [comment] 2017-07-17 12:10
@jungle-boogie I don't know what's going on. I recently got Miller building on Windows despite -- not because of -- any particular Windows knowledge on my part.

What I do have to offer is that in the Appveyor build (analog of Travis build) I can set up some 'build artifacts' associated with the builds. I haven't done this but when I do it'll simplify the flow. (At present, build artifacts for releases are built on a borrowed Windows laptop I'm using.)

**Comment by jungle-boogie** [comment] 2017-07-17 15:35
Hi @johnkerl,

Well I'm not attempting to build miller on my windows machine. Do I need additional build tools installed to run miller?

**Comment by johnkerl** [comment] 2017-07-19 03:03
@jungle-boogie to build from source you need MSYS2 as the build platform:

http://johnkerl.org/miller/doc/build.html#Windows_(beta)

Otherwise you can use the Appveyor artifacts once I set them up. I don't know of a third option, sadly.

**Comment by jungle-boogie** [comment] 2017-07-19 03:08
Hi John,

I'd prefer not to build from source and just use your binary + dlls. What I'm asking/wondering is if I *need* the build tools to use your binary.

Otherwise, I'll await appveyor to see if that will work.

**Comment by johnkerl** [comment] 2017-07-19 17:27
No you shouldn't need MSYS2 to use the binary+DLLs.

Appveyor it is! :)

**Comment by johnkerl** [comment] 2018-04-29 20:33
This is a duplicate of https://github.com/johnkerl/miller/issues/167

**Closed by johnkerl** 2018-04-29 20:33 UTC
