### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [johnkerl/miller#119] opened 2016-12-14 15:16 UTC
Dear John,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by johnkerl** [comment] 2016-12-14 15:37
@sergeevabc thanks for asking!!

This is a duplicate of https://github.com/johnkerl/miller/issues/109.

There's a bit more to it than having a compiler ...

* I don't have a Windows system but would spin up a VM easily enough -- not a big problem
* Bigger issue is Miller makes specific use of Unix-like features (by 'Unix-like' I mean Linux, BSD, OSX, ...) including the `popen` and `mmap` system calls which don't exist on Windows.

So I'd need some extended time on Windows to truly do a non-trivial port. It's worth doing -- you're not the first to ask -- but it's non-trivial to do.

**Closed** 2016-12-14 15:37 UTC
Labels: duplicate
