### ISSUE TITLE
JSON escaping issues with --jvquoteall

### ISSUE THREAD

**Issue by jgreely** [johnkerl/miller#261] opened 2019-08-14 06:02 UTC
[Miller 5.4.0, MacOS 10.14.6 (Homebrew install)]

Given the following CSV file:

```
a,b,c,d,e
"1,1","2
2","3","4\r4","5\n5"
```

Normal JSON output is correct, if you don't mind strings being converted to integers, but the `--jvquoteall` option doesn't escape the newline or the backslashes:

```
% mlr --icsv --ojson  cat in.csv 
{ "a": "1,1", "b": "2\n2", "c": 3, "d": "4\\r4", "e": "5\\n5" }

% mlr --icsv --ojson --jvquoteall cat in.csv 
{ "a": "1,1", "b": "2
2", "c": "3", "d": "4\r4", "e": "5\n5" }
```

**Comment by aborruso** [comment] 2019-08-14 15:32
In a CSV file you have real carriage return and line feed char, not escaped one. As that you have at the end of `"1,1","2` row.

Moreover I think it's a problem to have both `\r` and `\n`.

A right CSV should be

```
a,b,c,d,e
"1,1","2
2","3","4
4","5
5"
```

And if you run for this `mlr --icsv --ojson  cat  input.csv` you have

```
{ "a": "1,1", "b": "2\n2", "c": 3, "d": "4\n4", "e": "5\n5" }
```

And this is a right JSON.

**Comment by jgreely** [comment] 2019-08-14 18:49
No, my example is correct. Field "a" tests the quoted comma, "b" tests the quoted literal LF, "d" and "e" test the *string literals* "\r" and "\n", which should be passed through unmodified. This is done correctly in the standard JSON output, and incorrectly in the `--jvquoteall` output.

**Comment by aborruso** [comment] 2019-08-15 04:44
Ok, thank you for the updated example, because for me that CSV is in some way wrong.

I agree with you, --jvquoteall seems not work properly.

**Comment by johnkerl** [comment] 2019-09-02 19:31
Hello @jgreely and @aborruso -- I went to reproduce this and realized it's fixed by https://github.com/johnkerl/miller/commit/1d4d41d87cc6b66c47e6594a807e451fd82cb659 and so is part of https://github.com/johnkerl/miller/releases/tag/v5.5.0.

Sorry for the delay in reaching closure on this issue! :^/

```
$ cat gogo
cat > in.csv <<EOF
A,B,C,D,E
"1,1","2
2","3","4\r4","5\n5"
EOF

mlr --c2x cat in.csv
echo
mlr --icsv --ojson  cat in.csv
mlr --icsv --ojson  cat in.csv | jq .
echo
mlr --icsv --ojson --jvquoteall cat in.csv
mlr --icsv --ojson --jvquoteall cat in.csv | jq .
```

```
$ sh gogo
A 1,1
B 2
2
C 3
D 4\r4
E 5\n5

{ "A": "1,1", "B": "2\n2", "C": 3, "D": "4\\r4", "E": "5\\n5" }
{
  "A": "1,1",
  "B": "2\n2",
  "C": 3,
  "D": "4\\r4",
  "E": "5\\n5"
}

{ "A": "1,1", "B": "2\n2", "C": "3", "D": "4\\r4", "E": "5\\n5" }
{
  "A": "1,1",
  "B": "2\n2",
  "C": "3",
  "D": "4\\r4",
  "E": "5\\n5"
}
```

**Closed by johnkerl** 2019-09-02 19:31 UTC
Labels: bug
