### ISSUE TITLE
Notwithstanding `--skip-comments`, double-quoted tokens in comment are mishandled with any `--c2*` option

### ISSUE THREAD

**Issue by sphakka** [johnkerl/miller#1562] opened 2024-05-12 15:10 UTC
I'm possibly missing something, but can't get mlr (v6.12.0-dev) to work with comments containing double quotes:
```bash
$ echo -e '# Foo "bar" quux'  | mlr --skip-comments  --c2m cat
mlr: parse error on line 1, column 7: bare " in non-quoted-field.
``` 
Shouldn't it ignore the comment line altogether?

**Comment by aborruso** [comment] 2024-05-12 15:25
Hi @sphakka I have your same results.

A way to have an output is to change the input format in [csvlite](https://miller.readthedocs.io/en/latest/file-formats/#csvtsvasvusvetc), but it may not be suitable for your CSV input.

```
echo -e '# Foo "bar" quux\na,b\n1,2' | mlr --skip-comments --icsvlite --omarkdown cat
```

| a | b |
| --- | --- |
| 1 | 2 |

**Comment by sphakka** [comment] 2024-05-12 15:29
Thanks for the workaround, @aborruso!

**Comment by johnkerl** [comment] 2024-06-08 17:10
Closing this as a duplicate of #1346 (which needs doing) ...

**Closed by johnkerl** 2024-06-08 17:10 UTC
