### ISSUE TITLE
Unsparsify misaligns FILENAME references

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#371] opened 2020-09-14 09:01 UTC
Hi @johnkerl ,
I have these two input files (input01.txt and input02.txt):

```bash
cat input01.txt
a,b
2,3
4,5

cat input02.txt
a,b
8,3
12,5
```

If I run `mlr --c2p --barred cat then unsparsify then put '$FN=FILENAME' input0*.txt` I have wrong file names. I have this

```
+----+---+-------------+
| a  | b | FN          |
+----+---+-------------+
| 2  | 3 | input02.txt |
| 4  | 5 | input02.txt |
| 8  | 3 | input02.txt |
| 12 | 5 | input02.txt |
+----+---+-------------+
```

and not this

```
+----+---+-------------+
| a  | b | FN          |
+----+---+-------------+
| 2  | 3 | input01.txt |
| 4  | 5 | input01.txt |
| 8  | 3 | input02.txt |
| 12 | 5 | input02.txt |
+----+---+-------------+
```

Is it normal?

Thank you

**Comment by johnkerl** [comment] 2020-09-14 14:28
This is the same as https://github.com/johnkerl/miller/issues/303 I believe. Another thing that will be fixed in the Go port. :^/

**Comment by johnkerl** [comment] 2020-11-15 16:04
This is already working in the Go port

```
$ cat input02.txt
a,b
8,3

$ cat input02.txt
a,b
8,3
12,5

$ mlr --c2p cat then unsparsify then put '$FN=FILENAME' input0*.txt
a  b FN
2  3 input01.txt
4  5 input01.txt
8  3 input02.txt
12 5 input02.txt
```

**Comment by aborruso** [comment] 2020-11-15 16:46
Wow, I'm very happy!

Does the go port will be the greatest Christmas (2020) present ever?

**Comment by johnkerl** [comment] 2020-11-15 22:29
LOL, one can always hope for Christmas!! :) I don't know ... several verbs to port. Biggest work remaining is the remaining 'big' verbs: `stats1`, `stats2`, `merge-fields`, `step`, `join`, `nest`, `reshape`.

Also there's lots of regression-test to check off. Before making the Go implementation the release version, I want to be 100% sure I haven't unfixed any reported bugs, and that 100% of backward-incompatibilities are well-documented.

**Comment by johnkerl** [comment] 2020-11-15 22:33
@aborruso When I'm getting close and I've done everything I can find myself, I'll release a 5.10.1 with primary binaries being the C implementation but I'll also attach Go binaries and will ask power-users including yourself to test it out as much as possible.

The very worse-case outcomes are (a) I make the Go implementation the default too soon and I break people's workflows; (b) I make the Go implementation the default too soon and people stop using Miller :(.

**Comment by johnkerl** [comment] 2021-09-21 23:44
For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate

**Closed by johnkerl** 2021-09-21 23:44 UTC
Labels: bug, go-port
