### ISSUE TITLE
Discussion forum

### ISSUE THREAD

**Issue by derekmahar** [johnkerl/miller#176] opened 2018-05-25 16:03 UTC
Create a discussion forum where Miller users may talk about Miller.  Hosting suggestions:

- [Discourse](https://www.discourse.org/)
- [Fleep](https://fleep.io/)
- [FreeLists](https://www.freelists.org/)
- [Google Groups](https://groups.google.com/)
- [Keybase Team](https://keybase.io/blog/introducing-keybase-teams)
- [Slack](https://slack.com/)
- [Stride](https://www.stride.com/)

**Comment by johnkerl** [comment] 2018-10-08 01:09
@derekmahar do you have a preference from among the above?

**Comment by derekmahar** [comment] 2018-10-08 11:15
I think I'd choose [FreeLists](https://www.freelists.org/) or [Google Groups](https://groups.google.com/) because these are mailing list services that are free, searchable, mature, and likely to have longevity.

**Comment by johnkerl** [comment] 2019-02-06 20:26
See also
https://unix.stackexchange.com/tags/miller/info
created from
https://github.com/johnkerl/miller/issues/212

**Comment by aborruso** [comment] 2019-02-08 16:17
@derekmahar @johnkerl I think that [spectrum](https://spectrum.chat/features) and its kind of features would be a great choose.

I think that we could stay in two "spaces": a general one (stack exchange) to make millers known and to solve technical problems, and a community space (like spectrum) to talk about miller users, miller use cases, miller desired features.

**Comment by derekmahar** [comment] 2019-02-08 18:11
I've never used Spectrum, but it sounds good!  I hope the chat/discussion forums are less chaotic than the ones I've seen on Slack.

**Comment by johnkerl** [comment] 2019-04-27 16:07
@derekmahar Can we close this out as a duplicate of https://github.com/johnkerl/miller/issues/212 -- the StackExchange bit seems to be alive and well -- ?

**Comment by derekmahar** [comment] 2019-04-28 01:46
Like most own source projects, I think Miller would benefit from a few different communication forums.  While StackExchange is great for questions and answers, it's not really suitable for general discussion.

**Comment by derekmahar** [comment] 2019-11-02 14:17
[Reddit](https://www.reddit.com/) is another option.

**Comment by aborruso** [comment] 2019-11-02 14:29
Yes Reddit is a great idea

**Comment by johnkerl** [comment] 2021-01-18 15:40
@derekmahar @aborruso @nikosalexandris what about `/r/miller` ?

**Comment by johnkerl** [comment] 2021-01-18 15:42
Derp, that exists as does `/r/mlr` ...

**Comment by johnkerl** [comment] 2021-01-18 15:43
`/r/miller-tool` maybe? `/r/miller-discussion`?

**Comment by derekmahar** [comment] 2021-01-18 15:44
I like /r/miller-tool or even /r/miller-csv.  Too bad, though,that /r/miller and /r/mlr are already taken.

**Comment by aborruso** [comment] 2021-01-18 16:02
Ok for me R.

We have also GitHUB Discussions https://www.youtube.com/watch?v=DbTWBP3_RbM&feature=emb_title

**Comment by derekmahar** [comment] 2021-01-18 16:06
I had overlooked GitHub Discussions.  I think it's pretty new, but long overdue.

**Comment by johnkerl** [comment] 2021-01-18 23:30
@derekmahar ooh nice!

Here's a start ... https://github.com/johnkerl/miller/discussions/404

In a few days I can make a tweet, and Hacker News submission; anyone else feel free to socialize as well ...

**Comment by johnkerl** [comment] 2021-01-18 23:32
(I don't have enough Reddit Karma to creatre https://www.reddit.com/r/miller-tool/ ...)

**Comment by derekmahar** [comment] 2021-01-19 00:12
> (I don't have enough Reddit Karma to creatre https://www.reddit.com/r/miller-tool/ ...)

Nor do I.  I have only 1 karma.  I'm not a heavy Reddit user and read more content there than I write.

**Comment by derekmahar** [comment] 2021-01-19 00:13
> 
> 
> @derekmahar ooh nice!
> 
> Here's a start ... #404
> In a few days I can make a tweet, and Hacker News submission; anyone else feel free to socialize as well ...

@aborruso suggested GitHub Discussions, so I can't take credit, but I think it's a great suggestion!

**Comment by johnkerl** [comment] 2021-06-03 02:01
https://github.com/johnkerl/miller/discussions isn't high-volume (yet, anyway ...) -- in any case let's close this out, and revisit with a new issue if we want to create a new forum. Please re-open with comments if you'd like to continue this discussion! :)

**Closed by johnkerl** 2021-06-03 02:01 UTC
Labels: pending feedback to close, wishlist

**Comment by derekmahar** [comment] 2021-06-03 15:12
I think GitHub Discussions is a good choice.
