### ISSUE TITLE
Not a Logical Expression

### ISSUE THREAD

**Issue by spmundi** [johnkerl/miller#302] opened 2020-01-21 00:48 UTC
Why does this code not work:

mls --csv filter '$fielda != "" && strlen(fieldb) ==10'

I get an error telling me that it is not a logical expression. Both fielda and fieldb are strings.

**Comment by johnkerl** [comment] 2020-01-21 03:05
Hi @spmundi! Can you please copy/paste explicit input and output here? I can't reproduce.

Fixing the typos `mls` -> `mlr` and `fieldb` -> `$fieldb`, and inventing my own data

```
 cat t
fielda,fieldb
foo,abcdefgh
bar,abcdefghi
```

I get

```
$ mlr --csv filter '$fielda != "" && strlen($fieldb) ==10' t
fielda,fieldb
baz,abcdefghij
```

**Comment by spmundi** [comment] 2020-01-21 21:49
John
Here is exactly what I was doing.
Datafile is:
nsw_id,RNO,taxlot1,taxlot2
A002869,208652,,
A002870,R1351940,R1351940,R1351940
A002871,R1390710,R2111074,R2111074
A002872,R1086283,,
A002873,R138531,R0138531,R0138531
A002874,R65315,R0065253,R0065315
A002875,R636841,R0636841,R0636869
A002876,R491140,R0489135,R2123733
A002879,R461976,R0461976,R0461985
A002881,R641434,R0641434,R0641434
A002882,R624907,R624907,R624916
A002883,R610627,R0610627,R0610681
A002884,273288,00273288,01382569
A002885,R76811,R0076811,R0076811

And the command line was:
mlr --csv  filter '$taxlot1 != "" && strlen($RNO) != 10' datafile.csv

The application starts, then displays this output:
nsw_id,RNO,taxlot1,taxlot2
A002870,R1351940,R1351940,R1351940
A002871,R1390710,R2111074,R2111074
A002873,R138531,R0138531,R0138531
A002874,R65315,R0065253,R0065315
A002875,R636841,R0636841,R0636869
A002876,R491140,R0489135,R2123733
A002879,R461976,R0461976,R0461985
A002881,R641434,R0641434,R0641434
A002882,R624907,R624907,R624916
A002883,R610627,R0610627,R0610681
Expression does not evaluate to boolean: got MT_ERROR.

mlr --version
gives 5.4.0 as answer

**Comment by aborruso** [comment] 2020-01-21 22:15
> And the command line was:
> mlr --csv filter '$taxlot1 != "" && strlen($RNO) != 10' datafile.csv

I think you must add `-S` parameter

```
mlr --csv filter -S '$taxlot1 != "" && strlen($RNO) != 10' datafile.csv
```

`-S` keeps field values as strings with no type inference to int or float.

**Comment by spmundi** [comment] 2020-01-21 22:45
You know, this is exactly what tripped me up before.
I thought that a field like R1351940 would be sufficient to ensure that all subsequent instances of that filed (column) would be treated as a string, not an integer. Or possibly that the context (strlen()) would lead to an automatic conversion. 
Should there not be an error message to the effect "arg must be string" or something similar?

Sorry to have bothered everybody. This -s thing is not a mistake I will make again.

**Comment by johnkerl** [comment] 2020-01-22 18:09
Hi all -- Just catching up on the thread & have not yet run the repro.

I'll check it out & we may have a documentation opportunity.

**Comment by johnkerl** [comment] 2021-12-30 22:02
@spmundi I believe this is now resolved in Miller 6 -- please let me know if I'm mistaken and we can re-open ...


```
$ cat datafile.csv
nsw_id,RNO,taxlot1,taxlot2
A002869,208652,,
A002870,R1351940,R1351940,R1351940
A002871,R1390710,R2111074,R2111074
A002872,R1086283,,
A002873,R138531,R0138531,R0138531
A002874,R65315,R0065253,R0065315
A002875,R636841,R0636841,R0636869
A002876,R491140,R0489135,R2123733
A002879,R461976,R0461976,R0461985
A002881,R641434,R0641434,R0641434
A002882,R624907,R624907,R624916
A002883,R610627,R0610627,R0610681
A002884,273288,00273288,01382569
A002885,R76811,R0076811,R0076811

$ mlr --csv filter '$taxlot1 != "" && strlen($RNO) != 10' datafile.csv
nsw_id,RNO,taxlot1,taxlot2
A002870,R1351940,R1351940,R1351940
A002871,R1390710,R2111074,R2111074
A002873,R138531,R0138531,R0138531
A002874,R65315,R0065253,R0065315
A002875,R636841,R0636841,R0636869
A002876,R491140,R0489135,R2123733
A002879,R461976,R0461976,R0461985
A002881,R641434,R0641434,R0641434
A002882,R624907,R624907,R624916
A002883,R610627,R0610627,R0610681
A002885,R76811,R0076811,R0076811

$ mlr version
mlr version 6.0.0-rc for darwin/amd64/go1.16.5
```

**Closed** 2021-12-30 22:02 UTC
Labels: needs-documentation
