### ISSUE TITLE
Error in cookbook part 2?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#244] opened 2019-05-13 11:09 UTC
Hi,
int the cookbook there is [this recipe](https://johnkerl.org/miller/doc/cookbook2.html#Randomly_selecting_words_from_a_list):

    mlr --from data/english-words.txt --nidx filter 'n=strlen($1);4<=n&&n<=8' then sample -k 10

For me it does not work. 

I'm able to use it in this way

    mlr --from data/english-words.txt --n2c put '$n=strlen($1)' then filter '4<=$n && $n<=8' then sample -k 10

Thank you

**Comment by johnkerl** [comment] 2019-05-20 02:43
Yes, I get

```
$ mlr --from data/english-words.txt --nidx filter 'n=strlen($1);4<=n&&n<=8' then sample -k 10
Expression does not evaluate to boolean: got MT_ERROR.
```

but this should not be an error. Adding the `$` does help as a workaround, but, you should not have to. :^/

**Comment by johnkerl** [comment] 2019-05-20 02:50
The word `nan` is in `data/english-words.txt` which is a floating-point value (along with `inf`). This is a duplicate of https://github.com/johnkerl/miller/issues/241. For now you can use `filter -S`. I'll update the cookbook. Sorry about the error!!

```
 mlr --from data/english-words.txt --nidx filter -S 'n=strlen($1);4<=n&&n<=8' then sample -k 10
tinguy
nevus
acetenyl
macarism
incomer
pleonal
alepole
biconvex
psychal
arecolin
```

**Closed** 2019-05-20 02:53 UTC
